roxiness/routify.dev

scss/_c-sidebar-nav.scss
src/pages/sidebar.svelte

* example can be deleted when implemented

Provide example of a nested sidebar

---

scss/_c-navigation-mobile.scss
src/components/Accordion.svelte
src/components/NavItemMobile.svelte
src/components/NavItemsMobile.svelte

I implemented the accordion needed to fix #30 .
Well, at least the "visual part" of it and a bit of logic for closing and opening. Links are still hardcoded.
https://github.com/sveltech/routify-site-2020/issues/30

Implement accordion for mobile

---

CONTRIBUTING.md

I typed up a Contributing.md file.

Create Contributing.md for the website project

---

src/pages/docs/helpers/index.svelte

Cleaning up some code that was made when we did the functionDocs thing.

Clean up unused code

---

src/pages/index.svelte

I added a page title for "Home" but I was confused why I couldn't use the meta package for this.

Add a page title for the home page

---

src/components/home/Usps.svelte
src/components/nav/NavItemsMobileFragment.svelte
src/pages/guide/metadata.svelte
src/pages/guide/navigation.svelte

The third example was missing a ">" to close the list tag.
Without the example wont compile.

Fix invalid HTML in the third example

---

rollup.config.js
src/components/home/Usps.svelte
src/components/nav/NavItemsMobileFragment.svelte

Just a syntax fix for the rollup config file.

Tabs to spaces

---

static/__index.html

Add Plausible web analytics to test this. We're on a free trial for now, in a few days we can then check out the stats on the website.
If we don't like it/don't want to pay for it we can remove it.
As suggested by @kevmodrome

Add Plausible script

---

scss/_c-content.scss
scss/_e-base.scss
src/data.js
src/pages/blog/an-update.svx

New blog post

---

CONTRIBUTING.md
src/pages/guide/introduction/structure.svelte

Stumbled on those while browsing your docs.

tiny typos

---

src/pages/docs/helpers/_helpers/url.svelte

Added simple url function call example to the docs to make it clear you can call the function to get the current path.

Added URL function call example

---

scss/_c-blogpost-author.scss

Fix squishy faces on blog posts #146

---

src/pages/examples/auth.svelte

just misspelling

---

src/pages/guide/introduction/parameters.svelte

Closes https://github.com/sveltech/routify/issues/220

Additional global parameters documentation

---

scss/_c-navigation-mobile.scss

Addessed Issue #97. Open to feedback on size.

increased mobile nav font size

---

src/pages/guide/installation/install-to-existing-project.svelte

Adds build script in install-to-existing-project.svelte

add build script for existing project

---

src/pages/guide/starter-Template/overview.svelte

Adds starter template link to page on the first mention of "starter template" in the opening paragraph

add starter template link, ref #176

---

src/pages/docs/config/build.svelte

Fix a typo on the build configuration docs page

---

src/components/New.svelte

Improve alignment/CSS for new badge.
Just a slight quality improvement.
Signed-off-by: Wolfr <johan.ronsse@gmail.com>

Improve new badge

---

src/pages/guide/starter-Template/PWA_&_offline_first.svx

Added more instructions on how I implemented the PWA using Routify.
This is also with respect to the new merge regarding PWA Component lowercase/uppercase update.
Sorry about the previous PR, left a component outside the code block.

PWA Doc update

---

src/pages/examples/docker-setup.svx

I just created a guide about dockerize a routify webapp. Please give me feedback if something doesn't look right for you.

Create Docker guide

---

src/pages/examples/docker-setup.svx

I removed the instruction creating the dockerfile with touch

update docker setup

---

src/pages/docs/helpers/_helpers/afterPageLoad.svelte

Description changed from before load as it was probably copy/pasted from previous function

before URL changed to after page load

---

src/pages/guide/faq.md

Addresses: https://github.com/roxiness/routify/issues/343

Add FAQ for case insensitive routing

---

src/pages/docs/config/runtime.svelte

Hey folks!
Thanks for all your hard work on Routify. Got bitten by this recently, so here are some docs. Feel free to tweak!
Relevant issue:
https://github.com/roxiness/routify/issues/178
Cheers,
Thomas

Document data-routify="scroll-lock"
